apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-ui-filebeat
  namespace: ms-dev
data:
  filebeat.yml: |-
    filebeat.prospectors:
    - type: log
      paths:
        - /home/logs/flask-ui/*.log
      fields:
        env:  dev
        type: nginx
        service: flask-ui
      fields_under_root: true
    output.logstash:
      hosts: ['logstash-svc.elk:5044']