apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ui-1.7
  namespace: ms-prod
  labels:
    app: flask-ui
    version: "1.7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-ui
      version: "1.7"
  template:
    metadata:
      labels:
        app: flask-ui
        version: "1.7"
    spec:
      serviceAccountName: flask-ui-sa
      imagePullSecrets: 
      - name: harborsecret 
      containers:
      - name: flask-ui
        image: myhub.mydocker.com/ms-prod/flask-ui:1.7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 300m
            memory: 50Mi