apiVersion: v1
kind: Service
metadata:
  name: flask-ui
  namespace: ms-prod
  labels:
    app: flask-ui
    service: flask-ui
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: flask-ui
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-ui-sa
  labels:
    account: flask-ui