apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: ms-prod
data:
  mysql_username: 'ZGV2X3VzZXIK'
  mysql_password: 'YWJjMTIzNDU2Cg=='
  redis_password: "cmVkaXNfdXNlcgo="
  access_id: 'TFRBSTRHSFdwODNFVXc3OHNBallRaURRCg=='
  access_secret: 'SDI2OHRLMjRmcWpXcVJRR2pJdWY1ZHQ1a3F2anZ5Cg=='